### ISSUE TITLE
Errors thrown without reason by datatable customization

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#100]
:confetti_ball: 100th issue

# Scenario
- go to a page with a datatable without `data-number-rows-display` or `data-ordered-column-index` undefined

# Expected behavior
- default values are used
- no errors in the js console

# Current behavior
- default values are used
- errors appear in the js console

**Comment by Yann-BUTSCHER-EIRL** [comment]
Validated.
Closing this issue.
