### ISSUE TITLE
Member directory

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#101]
# Context
Now that the app allows to know if a people is a member or not, implement the member directory.

# Todo
- [x] enable button in the navbar
- [x] create the directory with only members in it
- [x] columns:
  - [x] Nom
  - [x] Prénom
  - [x] Mail
  - [x] Téléphone fixe
  - [x] Téléphone portable

**Comment by Yann-BUTSCHER-EIRL** [comment]
Validated.
Closing this issue.
