### ISSUE TITLE
CRUD of donations

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#106]
# Context
Create the CRUD for donations 

# Todo
- [x] Model
- [x] Controller
- [x] Repository
- [x] C
- [x] R
- [x] U
- [x] D

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL need testing

**Comment by LucileDT** [comment]
@hundrex need testing

**Comment by hundrex** [comment]
Create not okay, see #147 #148 #149 #152 and #154

**Comment by hundrex** [comment]
Read okay

**Comment by hundrex** [comment]
Update not okay, see #154 #155 #156 and #157

**Comment by hundrex** [comment]
Delete is okay
