### ISSUE TITLE
Uniformize the RU pages of the application

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#107]
# Context
See mockups.

# Todo
- [x] Connected user profile
- [x] Member
- [x] Membership
- [x] Donation
- [x] People
- [x] User

**Comment by LucileDT** [comment]
Waiting both #106 and #118 to be done before editing membership and donation pages.

**Comment by hundrex** [comment]
On /member/X pages the top of the table containing information is not at the same place than on the /people/X, /profile/X and /donation/X pages, resulting in an offset for all information.
On /people/X pages, the person name starts slightly farther than on the /member/X, /profile/X and /donation/X pages
