### ISSUE TITLE
Member edition does not work anymore

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#132]
# Scenario
- go to a member edition page
- click on the Save button

# Expected behavior
- changes are saved
- a confirmation message (green alert) is displayed

# Current behavior
- Symfony throws an error
![image](https://user-images.githubusercontent.com/23707217/74173695-d7c04800-4c32-11ea-946c-4297a588bf4b.png)

**Comment by Yann-BUTSCHER-EIRL** [comment]
@hundrex Can you test it please ?
