### ISSUE TITLE
Fields do not reset when creating new membership

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#133]
# Scenario
- go to the Create a new membership page
- Modify all the fields (do not save)
- reload the page by pressing F5

# Expected behavior
All the fields should go back to their initial state.

# Current behavior
Some fields are not reset:
- `Enregistrer une adhésion de type` (membership type)
- `Via` (Payment method)
- `Le` (Payment date)
- `Encaissés le` (Cashing date)
- `Commentaire sur l'adhésion` (Comment textbox)

Also note that reloading with `Ctrl`+`Shift`+`R` resets the fields as expected.

**Comment by Yann-BUTSCHER-EIRL** [comment]
@hundrex Can you test it please ?
