### ISSUE TITLE
Fixtures are broken

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#136]
# Scenario
- Delete the database
- Create an empty database
- Run the migration command: `bin/console doctrine:migration:migrate`
- Run the fixtures command: `bin/console doctrine:fixtures:load --append`

# Expected behavior
- Fixtures are run
- Data are inserted in the database

# Current behavior
An error happen: 
```
 > loading App\DataFixtures\DonationFixtures
   > loading App\DataFixtures\MembershipFixtures

In MembershipFixtures.php line 216:
                               
  Notice: Undefined offset: 0  
                               

doctrine:fixtures:load [--append] [--group GROUP] [--em EM] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

**Comment by Yann-BUTSCHER-EIRL** [comment]
The fix works for the described scenario.

But we also need to be able to load fixtures one by one if their dependencies are already loaded. Creating a new issue corresponding to this need.
