### ISSUE TITLE
Fixtures must be loadable one by one

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#138]
# Scenario
- Delete the database
- Create an empty database
- Run the migration command: `bin/console doctrine:migration:migrate`
- Run the user fixtures command: `bin/console doctrine:fixtures:load --append --group=UserFixtures`
- Run the membership fixtures command: `bin/console doctrine:fixtures:load --append --group=MembershipFixtures`

# Expected behavior
- Fixtures are run
- User data are inserted in the database in the first load
- Only membership data are inserted in the database in the second load

# Current behavior
An error happen:
```
$ bin/console doctrine:fixtures:load --append --group=MembershipFixtures

In SymfonyFixturesLoader.php line 146:
                                                                                                                                                                                        
  Fixture "App\DataFixtures\UserFixtures" was declared as a dependency for fixture "App\DataFixtures\MembershipFixtures", but it was not included in any of the loaded fixture groups.  
                                                                                                                                                                                        

doctrine:fixtures:load [--append] [--group GROUP] [--em EM] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by LucileDT** [comment]
I'm do not agree with this. The membership fixtures depends on the user ones because they need the users to be created. You shouldn't be able to run only the membership ones.

I think we should just systematically wipe the database and load fixtures from a fresh one @Yann-BUTSCHER-EIRL
