### ISSUE TITLE
Add sorting possibility on membership list table

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#143]
# Context
The membership list table allows to sort information by most of its column, bu not the `Encaissée le` one. It could be useful to be able to do that.

# Todo
- [x] Make membership list table sortable with its `Encaissée le` column

**Comment by Yann-BUTSCHER-EIRL** [comment]
@hundrex Can you test it please?

**Comment by LucileDT** [comment]
Would be nice to create an issue to make fixtures create different dates instead of `now()`, but otherwise, it works.
