### ISSUE TITLE
New donation form error labels are in English when application is in French

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#147]
# Scenario
- go to new donation form page in French
- try to register without putting a donation date

# Expected behavior
The error message printed when clicking on register should be in French

# Current behavior
The error message is in English

**Comment by hundrex** [comment]
It might be a good idea to also check for that error in all other forms.

**Comment by LucileDT** [comment]
![image](https://user-images.githubusercontent.com/23707217/80542097-b6a70200-89ac-11ea-858a-0f67e4cc9d3a.png)

It's in French for me

**Comment by hundrex** [comment]
Closed issue because it is caused by the browser locale and therefore cannot be changed
