### ISSUE TITLE
It is possible to register null and negative donations in new donation form

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#148]
# Scenario
- go to new donation registration page
- fill the form with needed information and with a negative or null (0) amount
- click on register

# Expected behavior
The form should display an error saying it is not possible to make a negative or null donation

# Current behavior
The information are registered without error

**Comment by LucileDT** [comment]
Fixed by 333bcb20730402a9b8eebb19062c86f873b4cffd
