### ISSUE TITLE
No error message on new donation form when amout is too high

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#149]
# Scenario
- go to new donation registration page
- fill the form with needed information and with a very high amount
- click on register

# Expected behavior
An error message should appear saying the amount is too high

# Current behavior
The amount box just becomes red, but no error message appears, therefore the user might not now what is wrong

**Comment by LucileDT** [comment]
Has been fixed by 333bcb20730402a9b8eebb19062c86f873b4cffd
