### ISSUE TITLE
Edit donation form error labels are in English when application is in French

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#155]
# Scenario
- go to edit donation form page in French
- try to register without putting an amount

# Expected behavior
The error message printed when clicking on register should be in French

# Current behavior
The error message is in English

**Comment by LucileDT** [comment]
Comes from the browser locale, try with a browser set in French (see https://developer.mozilla.org/fr/docs/Web/Guide/HTML/Formulaires/Validation_donnees_formulaire#Validation_selon_une_expression_r%C3%A9guli%C3%A8re the input in this section to test is your browser use French or English to display validation messages)

It's a known problem under linux distributions :roll_eyes:
