### ISSUE TITLE
The membership edition returns an error when editing "Normale" memberships

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#158]
# Scenario
- Drop your database
- Create a new one
- Load the migrations
- Load the fixtures
- Go to the membership list
- Edit a "Normale" one

# Expected behavior
The edition page should be shown

# Current behavior 
This error is shown when opening the edition page : 
`Return value of App\Entity\Payment::getPayer() must be an instance of App\Entity\People, null returned`
![image](https://user-images.githubusercontent.com/11696314/75694951-9c50f080-5ca9-11ea-8219-2da8bcb4d374.png)

**Comment by Yann-BUTSCHER-EIRL** [comment]
@hundrex Can you test it please ?

**Comment by LucileDT** [comment]
An error happens when loading fixtures

```
lapis@lapis-VirtualBox:~/developpement/structura$ bin/console doctrine:fixtures:load --append

   > loading App\DataFixtures\UserFixtures
   > loading App\DataFixtures\MembershipFixtures
   > loading App\DataFixtures\DonationFixtures
   > loading App\DataFixtures\TranslationFixtures

In MappingException.php line 94:
                                                          
  Class 'App\DataFixtures\MembershipType' does not exist  
```

**Comment by LucileDT** [comment]
See #159
