### ISSUE TITLE
Add the possibility to search people in the people list of donation edition and creation

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#164]
# Context
When creating or editing a donation, we have a list of people to select for the donator, but we can't search in this list, which could be tedious when there is a lot of people. It would be nice to be able to search in a likewise fashion than was has been done when selecting members for the memberships creation or edition.

# Todo
- [x] add a way to search in the people list on donation creation page
- [x] add a way to search in the people list on donation edition page

**Comment by LucileDT** [comment]
Fixed by 4c90c2db627a46f74ec3618371159377e8c5b485
