### ISSUE TITLE
Incoherent title and breadcrumb on donation edition page

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#170]
# Context
On the donation edition page, the title and breadcrumb does not show the complete page title "Edition du don de xxx€ du JJ MM YYYY" but only "Edition du don", which is incoherent because all the other pages have the entire page title and the tab title and breadcrumb.

# Todo
- [x] change the title of the donation edition page
- [x] change the breadcrumb of the donation edition page

**Comment by LucileDT** [comment]
As decided, I will instead change the page subtitle instead of the couple breadcrumb/title.
