### ISSUE TITLE
Uniformize title and breadcrumb names for profile edition pages

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#172]
# Context
On the four different profile edition pages (pseudo, password, personal information and newsletter), there are two kind of title used : 
- change **the** pseudo (used for pseudo and password)
- change **my** information (used for personal information and newsletter)
It would be great to use the same sentence for the four of them.

# Todo
- [x] choose between **the** or **my** option
- [x] change the title and breadcrumb for the two concerned pages

**Comment by LucileDT** [comment]
Il n'y a que my qui m'aille

**Comment by LucileDT** [comment]
(we will use "my")

**Comment by hundrex** [comment]
Ok for pseudo page, but you forgot the password page
