### ISSUE TITLE
Error when generating pdf receipt

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#182]
# Scenario
- Go to /receipt
- Generate a pdf for any year

# Expected behavior
The pdf should generate after waiting

# Current behavior
The pdf never appears, and an error is thrown in the messenger execution terminal : 
![MessengerError](https://user-images.githubusercontent.com/11696314/81825049-6bf1c200-9536-11ea-9fc8-65989fd5c0ba.png)

**Comment by LucileDT** [comment]
@hundrex please install locally the intl php extension by doing `apt-get install php7.2-intl`

**Comment by hundrex** [comment]
That worked
