### ISSUE TITLE
Automatically refresh receipt page when 

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#183]
# Context
When generating a receipt, the page shows an animated bar and disable the download button until the pdf is ready to be downloaded. Although, it does not automatically refresh the page, so the user might think that it will show when the process ends, and it might lead to confusion.
It would be better to regularly update the page so that the user can see when the process has ended. Time between refreshes should not be too short, as generating takes a long time (20 or 30 seconds might be enough)

# Todo
- [ ] Choose a time interval for the auto-refresh
- [ ] Implement the auto-refresh when pdf are generating

**Comment by LucileDT** [comment]
At the time you tested the page, it was not yet implemented. We don't do auto-F5 on the page, instead we display a message and color the table row in blue.

See e2eca9618615e2da91b69694ff3c4cdf36e25418
