### ISSUE TITLE
Error when creating new membership

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#193]
# Scenario
- Go to the new membership creation page
- Register a new membership (see bellow for the parameters I used)
- Click confirm on the modal

Parameters I used: 
![params](https://user-images.githubusercontent.com/11696314/82219200-3b869b00-991d-11ea-9622-d1be3478d6a4.png)

# Expected behavior
The membership should be registered, and the newly created membership page should appear

# Current behavior
An error got thrown: 
![Membership_bug](https://user-images.githubusercontent.com/11696314/82218921-e77bb680-991c-11ea-8674-3db386eebcdc.png)

**Comment by LucileDT** [comment]
@Parmifer would be cool if you tested the pages you work on before pushing your code.
