### ISSUE TITLE
Give a visual cue that show that the receipt is being generated in people pages

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#198]
# Context
When generating a receipt in /people/XX/generate/from-fiscal-year, there is a waiting time that varies in length. Even with the cursor showing a loading sign, it can be confusing for the user that there is nothing in the page showing that the receipt is being generated. It would be great to show something so that the user knows they have to wait.

# Todo
- [x] add a visual cue that informs the user they have to wait to get their receipt while it generates.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Visual clue added. Can you try it please?

**Comment by hundrex** [comment]
Does not work. After I selected the year in the list and clicked "Generate", the animation on the button shows for a slight moment then stops, the button is there again and the document is never generated.

**Comment by hundrex** [comment]
Re-tested it and mistake was on my side, I had not php7.2-intl installed on my VM. Everything works just fine with it, closing.

**Comment by LucileDT** [comment]
@hundrex could you open an issue about displaying an error when there is a server side problem preventing the pdf generation? Do not add it to any project, just create it so we will not forget this has to be done
