### ISSUE TITLE
Cumulated amount does not disapear from graph after donation deletion

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#229]
# Scenario
- Delete a donation that shows itself on the main page graph
- Refresh main page

# Expected behavior
The main page graph should not show the donation amount anymore

# Current behavior
The donation amount still shows but not with the donation curve, but with the cumulated one.

Note: it does not do this for memberships, even when removing enough to cut the donation amount of the membership to zero. It also does not do this when editing the donation amount, that updates just fine.

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL I think we have a problem with payment management in case of deletion of donation/membership, could you please check it?

- [ ] donation made alone deletion
- [ ] membership made alone deletion
- [ ] linked membership and donation deletion (we should decide what we want to do in this case)

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL I'll need your opinion on this
