### ISSUE TITLE
Migrations are broken (a successful serie by leszatypiques)

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#245]
# Scenario
- drop the database
- create the new database
- run the migrations

# Expected behavior
Migrations run smoostly.

# Current behavior
Migration `Version20200511151231` broke with an error `Call to a member function get() on null`.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Tested today and it worked. Closing.
