### ISSUE TITLE
Limit the  `check_number` field in forms to the number of characters it actually support

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#252]
# Scenario
- Go to a page where you can edit the check number information
- Input a number way too big

# Expected behavior
The form should tell you that there is a character limit to the field

# Current behavior
The form is submitted and leads to a symfony error, as the input is way too big for the database entry

**Comment by LucileDT** [comment]
- [ ] donation creation
- [ ] donation edition
- [ ] membership creation
- [ ] membership edition

**Comment by Yann-BUTSCHER-EIRL** [comment]
Tested and working. Closing.
