### ISSUE TITLE
Pages shown when user is not connected

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#265]
# Scenario
Without connecting, try to open Structura pages.

# Expected behavior
All of them should redirect to the login page.

# Current behavior
Some of them open and show a bit of data.

**Comment by LucileDT** [comment]
List of pages not redirecting:
- [ ] donation creation
- [ ] donations list
- [ ] donation details
- [ ] donation edition
- [ ] donation deletion

**Comment by Yann-BUTSCHER-EIRL** [comment]
Not fixed since pages :

- /profile/{id}/
- /profile/{id}/editpseudonym
- /profile/{id}/editpassword
- /profile/{id}/editpersonal
- /profile/{id}/editnewsletter

Are not redirecting to the login page but are returning an error.
