### ISSUE TITLE
Show people uppercased lastnames before their firstnames in all dropdowns

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#271]
# Context
When a user must chose a person from a list (dropdown), it would be easier to find the person if their lastname would be shown before their firstname and if the lastname were uppercased.

# Todo
- [x] Place the lastname before the first name in all dropdowns
  - [x] Membership add
  - [x] Membership edit
  - [x] Donation add
  - [x] Donation edit
- [x] Uppercase the lastname

**Comment by hundrex** [comment]
Accentuated letters are in lowercase, need to address that.
