### ISSUE TITLE
Swap first and last name on the persons lists

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#291]
# Context
It would make more sense to put the first name first and then the last name on the person lists.

# Todo
- [x] Swap first and last name on the persons lists
  - [x] home
  - [x] people_list
  - [x] contact_list
  - [x] member_list
  - [x] donation_list
  - [x] membership_list

**Comment by LucileDT** [comment]
I've made sure every table is ordered by lastname.
