### ISSUE TITLE
Error 500 when trying to get documentation at https://documentation.structura.associatif.online/

### ISSUE THREAD

**Issue by alexsedlex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#299]
When trying to access https://documentation.structura.associatif.online/ I obtain a blank page.
Network view shows that an internal server error occured

**Comment by LucileDT** [comment]
Thank you for opening an issue, indeed it's broken (if you are curious about the reason: the documentation was stored on a DokuWiki, but I had to update PHP to PHP8 on its server and did not take the time to also update the wiki engine).

I think I'll just move the wiki content to the GitHub repo, maintaining an external service is for now too much work for me. @Yann-BUTSCHER-EIRL do you agree with it? It means we will both have the technical wiki (in English) and the user wiki (in French) in Structura GitHub wiki.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Totally agree with you on this, we don't have the resources for now for maintaining an external wiki.

**Comment by LucileDT** [comment]
I have updated the wiki https://github.com/LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura/wiki

I will add to it user documentation tomorrow, @Yann-BUTSCHER-EIRL could you read the Contributing one please?

**Comment by Yann-BUTSCHER-EIRL** [comment]
I've read it, corrected some typos and mistakes. I do think that some required php extensions are missing but I'm not sure which ones.

**Comment by LucileDT** [comment]
@alexsedlex I close the issue but if you need anything, don't hesitate to ask here or open a new one :slightly_smiling_face:
