### ISSUE TITLE
Text input used for phone numbers set spaces between numbers

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#65]
# Context
When we use a form to save a phone number, it should separate each numbers pair by a space (only in the display, the data saved should be only 10 numbers without spaces) as it is the default French format.

# Todo
- [x] setup this field type to format the phone number

**Comment by sapphaos** [comment]
We might want to use this but it doesn't tell if the chars in the masks are added when the forms in returned : http://igorescobar.github.io/jQuery-Mask-Plugin/

All others solutions seem to require stripping the space between the characters so it's in the right format

**Comment by LucileDT** [comment]
I'm okay with adding a new jQuer library to do it. Here there is other libraries listed: https://css-tricks.com/input-masking
We will need to test them and see:
- if they are configurable (US phone numbers and FR phone numbers doesn't have the same mask)
- the best one in term of functionality (adding the mask on the placeholder, showing the mask on hover, ...)

**Comment by sapphaos** [comment]
They're configurable (the one I linked has an example of US phone number and  Sao Paulo phone number)
It works like this
https://www.registerone.com/how-to-setup-phone-input-field-masks-for-your-region-country/
It also seems that the masks add characters but that there are simple ways to delete those useless characters https://stackoverflow.com/questions/7854651/remove-literals-from-input-mask-after-form-submit

In the libraries you linked, the first example only seems to shows special characters of the mask, and not the text, so it can be confusing?  The second example uses a placeholder that is greyed out, we can use that if we find no mask library that shows on hover.

**Comment by LucileDT** [comment]
Ok to use the http://igorescobar.github.io/jQuery-Mask-Plugin if you prefer

**Comment by LucileDT** [comment]
This is fully bugged right now :confused:

**Comment by LucileDT** [comment]
Fix:
- [ ] portable phone number
- [ ] fax

Add warning:
- [ ] when phone number doesn't respect the rules

Add:
- [ ] all `0n` numbers except 06 and 07 in phone number
