### ISSUE TITLE
Add an empty user to people by default

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#84]
# Context
Currently when a member is created but have no user linked, it does not have a user at all. We need to change that so they will have an empty user instead of none.

# Todo
- [ ] add empty user on member creation
- [ ] add empty user on member creation in fixtures
- [ ] test it

**Comment by sapphaos** [comment]
An user can't be empty (it needs at least an username and a password) so an error is thrown when trying to add an empty user to a member on creation. 
![image](https://user-images.githubusercontent.com/26595575/62780887-fcd2d300-bab6-11e9-9111-0b278eafe31f.png)

**Comment by LucileDT** [comment]
I will try to edit the user to make those fields nullable.

**Comment by LucileDT** [comment]
Won't do as it's not mandatory
