### ISSUE TITLE
Add Payment

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#95]
# Todo
- [x] using the MCD, create the class and it's attributes
- [x] migrate

**Comment by LucileDT** [comment]
Missing an attribute telling who is the author of the Payment

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL You need to test the two modifications I made (adding attribute and editing fixtures)
