### ISSUE TITLE
Add PaymentType

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#96]
# Todo
- [x] using the MCD, create the class and it's attributes
- [x] migrate
- [x] add default types:
  - [x] `Espèces`
  - [x] `Carte Bleue`
  - [x] `Virement`
  - [x] `Chèque`
  - [x] `HelloAsso`

**Comment by LucileDT** [comment]
How can I test it?
